### ISSUE TITLE
LOSITO Validation

### ISSUE THREAD

**Issue by etolley** [epfl-radio-astro/pypeline#10]
Goal: check accuracy of BB reconstruction, produce dataset to make nice set of validation results as in https://arxiv.org/pdf/2111.03249.pdf
Steps:

1. make set of true .fits images
2. make set of MS observations
3. make set of reconstructed WSLCEAN obs
4. make set of reconstructed BB obs (SS, then NUFFT)
5. compare dirty vs dirty
6. compare WSCLEAN dirty vs masked dirty BB

**Comment by micbia** [comment]
task 1 to 3 are done. The data are stored on the `/project/c31/ `scratch folder on daint, with the name `losito_RADIO_images/`.
For task 4, we need to figure out where the OOM error in the NUFFT is coming from when requiring 60 stations and more than 4 eigenlevels.
For tasks 5 and 6 we have some preliminary results, shown on Mar. 3th RA meeting. In the former, BB seems to reconstruct the same dirty image (eye comparison), but further analysis for issue #18 should confirm that. The latter, preliminary results show that the eigenlevel decomposition of BB is doing better at detecting the region with sources (thresholding mask)
